### ISSUE TITLE
ux: filling in only affiliation name doesn't work

### ISSUE THREAD

**Issue by slint** [inveniosoftware/react-invenio-deposit#119]
Package version (if known): v0.8.4

## Describe the bug

In the deposit form, if you fill in for a creator/contributor only the affiliation name, the form fails to be submitted.

## Steps to Reproduce

1. Go to a fresh upload form
2. Fill in family name, given name, and affiliation name
3. Click "save draft"
4. Nothing happens (because of JS error, that tries to serialize affiliation identifiers)

## Expected behavior

It should be possible to only fill-in the affiliation's name without any identifiers.

## Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/1814661/100363727-715bb900-2ffd-11eb-8a64-1f252febdd22.png)

**Comment by zzacharo** [comment]
closed by #121
