### ISSUE TITLE
propTypes is not defined while running tests

### ISSUE THREAD

**Issue by audrium** [inveniosoftware/react-invenio-deposit#129]
Package version (if known): 0.9.0

## Describe the bug
`propTypes` is not defined in the project while running tests and therefore it fails.
Example: https://github.com/inveniosoftware/react-invenio-deposit/runs/1510036927?check_suite_focus=true#step:5:27

## Expected behavior
Components like `RemoteSelectField` should have their `propTypes` as defined in the component files

## Additional context
While running tests `RemoteSelectField.propTypes` is `undefined`, only `defaultProps` are available

**Comment by zzacharo** [comment]
closed by https://github.com/inveniosoftware/react-invenio-forms/pull/35
