### ISSUE TITLE
Question: Multiple Publishers?

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/react-invenio-deposit#14]
See #4 

Data Model Question: (implications extend beyond just frontend and into backend)

Can this field be repeatable? If the record contains multiple publishers. This came up from librarians on our side: we have 105 deposits with multiple publishers (only 1.4% of our collection).

**Comment by lnielsen** [comment]
I've discussed this with multiple people and the consensus was that only a single publisher is needed. Worst case you can add multiple publisher names in the field. I'm closing the issue, but the discussion is still open as part of the final review of the data model.
