### ISSUE TITLE
licenseField: search a standard license is broken if have already chosen one from the list

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/react-invenio-deposit#152]
Package version (if known): v0.9.9

## Describe the bug
In the licenseField, when you try to search for a standard license, the searchbar component is not accepting the `space` character. This is happening if after selecting a license you try to search for another one.

## Steps to Reproduce
1. Go to deposit form
2. Click on "Add license -> Add Standard"
3. Click on one of the license results.
4. Search in the searchbar for a value containing a space.
5. See that space is not typed and notice that the license dropdown, the one triggered the modal to open, is being toggled from the space key.

**Comment by fenekku** [comment]
I think related is:

After selecting a license and adding another one. The space character in the `description` field is not accepted. For instance:

![image](https://user-images.githubusercontent.com/1932651/104058057-c5d78400-51b8-11eb-8b9d-5e72f9c69415.png)
