### ISSUE TITLE
fileUploader: files are not shown when you edit a published record

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/react-invenio-deposit#174]
Package version (if known): <version>

## Describe the bug
The files are not shown when you edit a published record.
<img width="918" alt="Screenshot 2021-01-26 at 16 55 19" src="https://user-images.githubusercontent.com/22594783/105869221-4c80c380-5ff7-11eb-8499-b7994e6b8c45.png">

## Expected behavior

We should list the files and show the warning message that exists when create/edit a draft.

## Screenshots (if applicable)
![Screenshot_2021-01-26_at_16 38 33](https://user-images.githubusercontent.com/22594783/105869379-776b1780-5ff7-11eb-965b-6dc46140f496.png)

**Comment by fenekku** [comment]
Seems to have been fixed since: I can't reproduce with latest from master.
