### ISSUE TITLE
files: available storage header is broken

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/react-invenio-deposit#190]
When the "Storage available" header is overflowing the component is broken. See:

<img width="730" alt="Screenshot 2021-02-02 at 15 20 40" src="https://user-images.githubusercontent.com/22594783/106613370-64fa5c00-656a-11eb-9f02-7802c3552e6b.png">

We should fix the header to remain in the same line or continue in the next one altogether.

**Comment by zzacharo** [comment]
A quick fix can be applied for devices `>=994px`. See
<img width="1672" alt="Screenshot 2021-02-04 at 18 44 53" src="https://user-images.githubusercontent.com/22594783/106933475-3ec6ee80-6719-11eb-8628-4c483276be1e.png">

For smaller devices, bigger changes are required. My question is: Do we want to start fixing responsiveness for screens like tablets and mobiles at this moment or currently the fix applying to the screenshot is good enough?

**Comment by fenekku** [comment]
oh I thought a quick fix like Mojib did here: https://github.com/inveniosoftware/invenio-app-rdm/pull/519/files would have done it.

**Comment by zzacharo** [comment]
In general I think we should integrate the SUI regarding responsiveness https://react.semantic-ui.com/collections/grid/#responsive-variations-responsive-width
