### ISSUE TITLE
deposit form: integrate subjects component

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/react-invenio-deposit#330]
double subjects label
![Screenshot 2021-07-12 at 10 19 22](https://user-images.githubusercontent.com/6756943/125255077-5bd0a080-e2fb-11eb-9a27-fdc03ae1a61e.png)

**Comment by fenekku** [comment]
Fixed in https://github.com/inveniosoftware/invenio-app-rdm/pull/925
