### ISSUE TITLE
Bug: i18next scanner

### ISSUE THREAD

**Issue by mb-wali** [inveniosoftware/react-invenio-deposit#348]
i18next scanner - has some issue while extracting messages only if the strings are marked with `Trans` component.
the issue is that it passes the key to values for other languages rather than only to eng language.

_Originally posted by @mb-wali in https://github.com/inveniosoftware/react-invenio-deposit/issues/345#issuecomment-882636917_

**Comment by zzacharo** [comment]
Related issue https://github.com/i18next/i18next-scanner/issues/187

**Comment by rekt-hard** [comment]
see https://github.com/inveniosoftware/react-invenio-deposit/issues/591
