### ISSUE TITLE
files: handle file initialization failure

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/react-invenio-deposit#382]
Package version (if known): v6.0

## Describe the bug
When a file is failing to be initialized the error is not reported in the UI. 

## Steps to Reproduce
1. Go to the uploads page and save a draft without files
2. Open a new window and navigate to the same draft
3. Upload a file e.g test.txt to one of the 2 windows
4. Now try to upload the same to the other one
5. The error that you can see in the network panel is that the file already exists thus it's failing to get initialized

## Expected behavior

We should report the error in the screen similar to #381 
## Screenshots (if applicable)
<img width="1291" alt="Screenshot 2021-08-31 at 19 45 34" src="https://user-images.githubusercontent.com/22594783/131847941-67fe5bfd-ba2e-47fe-ab42-3e23920cf777.png">

**Comment by kpsherva** [comment]
it was implemented
