### ISSUE TITLE
Removing license doesn't behave correctly

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/react-invenio-deposit#387]
(transferred from @carsonicator reports at NU)

## Package version (if known)

6.0

## Browser Versions Tested

Chrome: Version 93.0.4577.63 (Official Build) (x86_64)
Safari: Version 14.1.2 (15611.3.10.1.7, 15611)

## Describe the bug

When trying to remove an added license by clicking the 'Remove' button, the license does not disappear until the browser is refreshed. The behavior is the same for the Chrome and Safari versions I tested.

## Steps to Reproduce

1. Create a record
2. Choose a license in addition to the default one
3. Click the 'Remove' button
4. Observe bug
5. Refresh browser and see that the license has been removed.

**Comment by zguillen** [comment]
Our users also noticed this bug.  The behavior we are seeing is that licenses cannot be removed until a record is saved as a draft.  Then the behavior is as expected.
