### ISSUE TITLE
creatibutors modal: add support suggestion and autofill 

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/react-invenio-deposit#397]
- [x] Add a top level search field, 
![Deposit__Creators_auto-completion_4](https://user-images.githubusercontent.com/6756943/143221178-2fe423d4-474c-4b87-a494-5a34172e7925.png)

- [x] Display suggestions
![Deposit__Creators_auto-completion_2](https://user-images.githubusercontent.com/6756943/143221190-d451da52-a301-4dee-bdca-74a7062a2016.png)

- [x] Autofill the form when one of the suggestions is chosen
![Deposit__Creators_auto-completion_3](https://user-images.githubusercontent.com/6756943/143221192-8c1683a2-8bb8-4a8d-b1d6-32ba6891aa0f.png)
ld

- [x] Make modal collapsable
![Deposit__Creators_auto-completion_1](https://user-images.githubusercontent.com/6756943/143221444-72db2542-05ed-46b6-8dd2-0e76a122fcc2.png)

**Comment by ppanero** [comment]
Comments regarding the implementation done in [zenodo/react-invenio-deposit](https://github.com/zenodo/react-invenio-deposit): Avoid using `createRef` for affiliations and identifiers. Instead use local component state + formik state + passing handlers as prop.

**Comment by slint** [comment]
Closed via #410
