### ISSUE TITLE
Initial deposit page form fields (not finessed)

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/react-invenio-deposit#4]
We are going to have to implement the deposit page form fields. Starting from this mockup

![2020_04_21_Deposit page details](https://user-images.githubusercontent.com/1932651/81321444-38a3c480-9058-11ea-935a-2310f0764745.png)

but simplifying things as much as we can for this first pass. Goal is to just get a sense for integration and get minimum viable form field in each case.

- [x] title
- [x] Creators + Contributors
- [x] Resource type
- [ ] Subjects #7 
- [ ] Description #8 
- [ ] Language #9 
- [ ] Publication Date #10 
- [ ] License #11 
- [ ] Dates #12 
- [ ] Version #13 
(- [ ] Publisher #14  (not in the backend so can ignore for now))
- [ ] Related Work #15 
- [ ] References #15 
- [ ] Awards #16 
- [ ] Funding #16 
- [ ] DOI #17 
- [ ] Location #20 
- [ ] TODO: add any other missing

**Comment by ppanero** [comment]
Closing this since most of the linked issues are closed. Only locations are missing, but they will come later on. Please reopen if needed
