### ISSUE TITLE
serializers: keep to minimal the transformation between REST Api and UI

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/react-invenio-deposit#42]
We should feed the UI components as much as we can with the same objects/fields (i.e schema) that we receive from the API response. This will make easier the understanding of the data format that the components are expecting and might decomplexify the debugging of issues in the future.

**Comment by fenekku** [comment]
As much as we can, we should. Identifiers in the backend are stored in a dict and formik only allows us to manipulate arrays, so there will be some discrepancies like this.
