### ISSUE TITLE
ArrayField: error message only displayed for the first element

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/react-invenio-deposit#447]
Package version (if known): v0.18.0
## Describe the bug
When adding different elements to an ArrayField cmp such as "Alternate identifiers" or "Related works", if there are more than one element with errors only the first one is shown.

## Steps to Reproduce
1. Go to 'New upload'.
2. Fill in basic information.
3. Add 2 or more "Alternate identifiers" or "Related works" elements.
4. Click "Save draft".
5. See the errors in the banner.
6. Scroll down and see only the first element highlighted with the error message.

## Expected behavior
All fields with error should be highlighted.

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/15194802/157409995-a1af667c-f45c-4f5c-b631-c7dbf82ca209.png)

**Comment by NRodriguezcuellar** [comment]
cannot be reproduced anymore
