### ISSUE TITLE
remove ignore for eslint rule when releasing 0.20

### ISSUE THREAD

**Issue by NRodriguezcuellar** [inveniosoftware/react-invenio-deposit#563]
If this PR is merged: https://github.com/inveniosoftware/react-invenio-deposit/pull/551 the `fieldPath` propType will be set to `isRequired` and following our https://github.com/inveniosoftware/eslint-config-invenio eslint rules we should remove the defaultProps set for `fieldPath`. Because this will break backwards compatibility with older instances of invenio-app-rdm instead of removing the defaultProps we will ignore the rule, only for this specific prop.

This ignore should be removed after releasing a new minor version.

**Comment by zzacharo** [comment]
https://github.com/inveniosoftware/react-invenio-deposit/pull/551/files#diff-3d784b4dfa34800c50614a2b4dc56a3cbc158d84aa58994a8ee9ba7e5a82558dR44
