### ISSUE TITLE
ux: bold/visually differentiate the top-level form fields

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/react-invenio-deposit#88]
The top-level form fields have the same font characteristics as the sub fields. This makes it especially hard to differentiate between top-level required fields and sub-level required fields (i.e. fields that are required only if filled).

We should make top-level fields visually different somehow.

**Comment by lnielsen** [comment]
- Increase font-size of top-level fields labels.
- Remove bold from subfield labels.

Currently:

![Screenshot 2021-02-02 at 17 03 05](https://user-images.githubusercontent.com/1698163/106626988-9712ba80-6578-11eb-94f3-d88dad155040.png)


Desired endstate:

![Screenshot 2021-02-02 at 17 02 52](https://user-images.githubusercontent.com/1698163/106626919-7ea2a000-6578-11eb-91b2-819dadaf4056.png)
