### ISSUE TITLE
Add LanguagesField

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/react-invenio-deposit#9]
See #4 

Data Model Question:

Can this field be repeatable? If the record contains multiple languages the https://en.wikipedia.org/wiki/ISO_639-3 code `mul` can be used but it doesn't specify which languages. This came up from librarians on our side.

**EDIT**
Yes, multiple languages are supported.

**Comment by lnielsen** [comment]
Yes, it's a repeatable field in the new data model.
